name: Maven Build CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    uses: durgavinayb/githubWorkflows/.github/workflows/maven.yml@main

  deploy:
    needs: build
    uses: durgavinayb/githubWorkflows/.github/workflows/tomcat.yml@main
